#!/usr/bin/env python3
"""Tiny drawing + export helpers for LED-matrix pixel art.

A Canvas is a character grid plus a palette mapping each character to an RGB
triple, which keeps the artwork readable as source and lets `ascii_art()` act
as a diff-able record of the drawing.
"""

import json
import os

from PIL import Image, ImageDraw


class Canvas:
    def __init__(self, palette, width=16, height=16, bg="."):
        self.palette = palette
        self.w = width
        self.h = height
        self.grid = [[bg for _ in range(width)] for _ in range(height)]

    # --- drawing -----------------------------------------------------------
    def put(self, x, y, ch):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.grid[y][x] = ch

    def puts(self, points, ch):
        for x, y in points:
            self.put(x, y, ch)

    def rect(self, x0, y0, x1, y1, ch):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.put(x, y, ch)

    def disc(self, cx, cy, r, ch):
        """Filled circle in cell-center coordinates."""
        for y in range(self.h):
            for x in range(self.w):
                if (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2 <= r * r:
                    self.put(x, y, ch)

    def ring(self, cx, cy, r_outer, r_inner, ch):
        for y in range(self.h):
            for x in range(self.w):
                d2 = (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2
                if r_inner * r_inner < d2 <= r_outer * r_outer:
                    self.put(x, y, ch)

    def mirror_x(self, chars=None):
        """Copy the left half onto the right, for symmetric subjects."""
        for y in range(self.h):
            for x in range(self.w // 2):
                ch = self.grid[y][x]
                if chars is None or ch in chars:
                    self.grid[y][self.w - 1 - x] = ch

    # --- output ------------------------------------------------------------
    def pixels(self):
        return [[self.palette[ch] for ch in row] for row in self.grid]

    def ascii_art(self):
        return "\n".join("".join(row) for row in self.grid)

    def emit(self, name, outdir="."):
        """Write <name>.png, <name>_preview.png, <name>.json and <name>.h."""
        px = self.pixels()
        path = lambda ext: os.path.join(outdir, name + ext)  # noqa: E731

        img = Image.new("RGB", (self.w, self.h))
        img.putdata([px[y][x] for y in range(self.h) for x in range(self.w)])
        img.save(path(".png"))

        # Blow-up with a faint grid so single pixels stay countable.
        scale = 32
        big = img.resize((self.w * scale, self.h * scale), Image.NEAREST)
        d = ImageDraw.Draw(big)
        for i in range(1, max(self.w, self.h)):
            d.line([(i * scale, 0), (i * scale, self.h * scale)], fill=(60, 60, 70))
            d.line([(0, i * scale), (self.w * scale, i * scale)], fill=(60, 60, 70))
        big.save(path("_preview.png"))

        with open(path(".json"), "w") as f:
            json.dump(
                {
                    "width": self.w,
                    "height": self.h,
                    "order": "row-major, top-left origin",
                    "rows_hex": ["".join("%02X%02X%02X" % p for p in r) for r in px],
                    "pixels_rgb": px,
                },
                f,
                indent=2,
            )

        def rgb565(p):
            r, g, b = p
            return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

        n = self.w * self.h
        out = [
            "// %dx%d LED-matrix art. Row-major, top-left origin." % (self.w, self.h),
            "// Generated by the matching generator script -- do not edit by hand.",
            "#pragma once",
            "#include <stdint.h>",
            "",
            "#define %s_W %d" % (name.upper(), self.w),
            "#define %s_H %d" % (name.upper(), self.h),
            "",
            "static const uint32_t %s_rgb888[%d] = {" % (name, n),
        ]
        out += ["    " + " ".join("0x%02X%02X%02X," % p for p in r) for r in px]
        out += ["};", "", "static const uint16_t %s_rgb565[%d] = {" % (name, n)]
        out += ["    " + " ".join("0x%04X," % rgb565(p) for p in r) for r in px]
        out += ["};", ""]
        with open(path(".h"), "w") as f:
            f.write("\n".join(out))
