#!/usr/bin/env python3
"""Tiny drawing + export helpers for LED-matrix pixel art.

A Canvas is a character grid plus a palette mapping each character to an RGB
triple, which keeps the artwork readable as source and lets `ascii_art()` act
as a diff-able record of the drawing.
"""

import json
import os

from PIL import Image, ImageDraw


def mix(a, b, t):
    """Blend two RGB triples; t=0 gives a, t=1 gives b."""
    t = max(0.0, min(1.0, t))
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(3))


def dim(c, f):
    return tuple(max(0, min(255, int(round(v * f)))) for v in c)


def shift_rows(px, rows, dx):
    """Slide the given rows sideways, for one-frame glitch tears."""
    out = [list(r) for r in px]
    w = len(px[0])
    for y in rows:
        if 0 <= y < len(px):
            out[y] = [px[y][(x - dx) % w] for x in range(w)]
    return out


class Canvas:
    def __init__(self, palette, width=16, height=16, bg="."):
        self.palette = palette
        self.w = width
        self.h = height
        self.grid = [[bg for _ in range(width)] for _ in range(height)]

    # --- drawing -----------------------------------------------------------
    def put(self, x, y, ch):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.grid[y][x] = ch

    def puts(self, points, ch):
        for x, y in points:
            self.put(x, y, ch)

    def rect(self, x0, y0, x1, y1, ch):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.put(x, y, ch)

    def disc(self, cx, cy, r, ch):
        """Filled circle in cell-center coordinates."""
        for y in range(self.h):
            for x in range(self.w):
                if (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2 <= r * r:
                    self.put(x, y, ch)

    def ring(self, cx, cy, r_outer, r_inner, ch):
        for y in range(self.h):
            for x in range(self.w):
                d2 = (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2
                if r_inner * r_inner < d2 <= r_outer * r_outer:
                    self.put(x, y, ch)

    def mirror_x(self, chars=None):
        """Copy the left half onto the right, for symmetric subjects."""
        for y in range(self.h):
            for x in range(self.w // 2):
                ch = self.grid[y][x]
                if chars is None or ch in chars:
                    self.grid[y][self.w - 1 - x] = ch

    # --- output ------------------------------------------------------------
    def pixels(self):
        return [[self.palette[ch] for ch in row] for row in self.grid]

    def ascii_art(self):
        return "\n".join("".join(row) for row in self.grid)

    def emit(self, name, outdir="."):
        """Write <name>.png, <name>_preview.png, <name>.json and <name>.h."""
        px = self.pixels()
        path = lambda ext: os.path.join(outdir, name + ext)  # noqa: E731

        img = Image.new("RGB", (self.w, self.h))
        img.putdata([px[y][x] for y in range(self.h) for x in range(self.w)])
        img.save(path(".png"))

        # Blow-up with a faint grid so single pixels stay countable.
        scale = 32
        big = img.resize((self.w * scale, self.h * scale), Image.NEAREST)
        d = ImageDraw.Draw(big)
        for i in range(1, max(self.w, self.h)):
            d.line([(i * scale, 0), (i * scale, self.h * scale)], fill=(60, 60, 70))
            d.line([(0, i * scale), (self.w * scale, i * scale)], fill=(60, 60, 70))
        big.save(path("_preview.png"))

        with open(path(".json"), "w") as f:
            json.dump(
                {
                    "width": self.w,
                    "height": self.h,
                    "order": "row-major, top-left origin",
                    "rows_hex": ["".join("%02X%02X%02X" % p for p in r) for r in px],
                    "pixels_rgb": px,
                },
                f,
                indent=2,
            )

        n = self.w * self.h
        out = [
            "// %dx%d LED-matrix art. Row-major, top-left origin." % (self.w, self.h),
            "// Generated by the matching generator script -- do not edit by hand.",
            "#pragma once",
            "#include <stdint.h>",
            "",
            "#define %s_W %d" % (name.upper(), self.w),
            "#define %s_H %d" % (name.upper(), self.h),
            "",
            "static const uint32_t %s_rgb888[%d] = {" % (name, n),
        ]
        out += ["    " + " ".join("0x%02X%02X%02X," % p for p in r) for r in px]
        out += ["};", "", "static const uint16_t %s_rgb565[%d] = {" % (name, n)]
        out += ["    " + " ".join("0x%04X," % rgb565(p) for p in r) for r in px]
        out += ["};", ""]
        with open(path(".h"), "w") as f:
            f.write("\n".join(out))


def rgb565(p):
    r, g, b = p
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def emit_animation(name, frames, outdir=".", delay_ms=100, scale=32,
                   include_rgb888=None):
    """Write <name>_anim{.gif,_preview.gif,.json,.h} for a list of frames.

    Each frame is a pixel matrix: rows of (r, g, b) tuples, as produced by
    Canvas.pixels().

    include_rgb888 defaults to dropping the 32-bit array on long animations:
    past a few dozen frames it doubles a header that an MCU cannot use anyway,
    since anything of that length is played from the RGB565 copy.
    """
    if include_rgb888 is None:
        include_rgb888 = len(frames) <= 64
    h = len(frames[0])
    w = len(frames[0][0])
    base = os.path.join(outdir, name + "_anim")

    def to_image(px, s=1):
        im = Image.new("RGB", (w, h))
        im.putdata([px[y][x] for y in range(h) for x in range(w)])
        return im.resize((w * s, h * s), Image.NEAREST) if s > 1 else im

    def save_gif(path_, s):
        # Per-frame adaptive palettes: the glow ramps introduce more distinct
        # colors across the loop than a single 256-entry GIF palette holds
        # comfortably, and each individual frame uses only a handful.
        imgs = [to_image(f, s).convert("P", palette=Image.ADAPTIVE) for f in frames]
        imgs[0].save(
            path_,
            save_all=True,
            append_images=imgs[1:],
            duration=delay_ms,
            loop=0,
            disposal=2,
            optimize=False,
        )

    save_gif(base + ".gif", 1)
    save_gif(base + "_preview.gif", scale)

    with open(base + ".json", "w") as f:
        json.dump(
            {
                "width": w,
                "height": h,
                "frame_count": len(frames),
                "delay_ms": delay_ms,
                "order": "row-major, top-left origin",
                "frames_rows_hex": [
                    ["".join("%02X%02X%02X" % p for p in r) for r in fr]
                    for fr in frames
                ],
            },
            f,
            indent=2,
        )

    n = w * h
    up = name.upper()
    out = [
        "// %dx%d LED-matrix animation, %d frames at %d ms."
        % (w, h, len(frames), delay_ms),
        "// Row-major, top-left origin. Generated -- do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define %s_ANIM_W %d" % (up, w),
        "#define %s_ANIM_H %d" % (up, h),
        "#define %s_ANIM_FRAMES %d" % (up, len(frames)),
        "#define %s_ANIM_DELAY_MS %d" % (up, delay_ms),
        "",
    ]
    if include_rgb888:
        out.append(
            "static const uint32_t %s_anim_rgb888[%d][%d] = {" % (name, len(frames), n)
        )
        for fr in frames:
            out.append("    {")
            out += ["        " + " ".join("0x%02X%02X%02X," % p for p in r) for r in fr]
            out.append("    },")
        out += ["};", ""]
    else:
        out += ["// RGB888 array omitted: %d frames. Play from the RGB565 copy."
                % len(frames), ""]
    out.append(
        "static const uint16_t %s_anim_rgb565[%d][%d] = {" % (name, len(frames), n)
    )
    for fr in frames:
        out.append("    {")
        out += ["        " + " ".join("0x%04X," % rgb565(p) for p in r) for r in fr]
        out.append("    },")
    out += ["};", ""]
    with open(base + ".h", "w") as f:
        f.write("\n".join(out))
